all:
	gcc  -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Wall -Werror -std=c99 main.c list.c list.h stack.c stack.h monotone-chain.c monotone-chain.h util.c util.h -o main
run:
	./main
