listsMain:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Wall -Werror -std=c99 lists-main.c ../ATDs/list.c ../ATDs/list.h ../ATDs/stack.c ../ATDs/stack.h ../util.c -o lists-main
run-listsMain:
	./lists-main
